device: cuda:0
patch_size: 128

school:
  model_name: efficientnet-b0

augs:
  train:
    yaml: /dgx/github/STAD/stad/yamls/train_augmentations.yaml
    updates:
      - name: ProbabilisticCrop
        args:
          height: ${patch_size}
          width: ${patch_size}
  val:
    yaml: /dgx/github/STAD/stad/yamls/test_augmentations.yaml
    updates:
  test:
    yaml: /dgx/github/STAD/stad/yamls/test_augmentations.yaml
    updates:

dataset:
  name: MVTecDataset
  base: /dgx/github/STAD/data
  train:
    query:
      - category == 'bottle' &
        data_type == 'train' &
        defect_type == 'good'
  val:
    query:
      - category == 'bottle' &
        data_type == 'train' &
        defect_type == 'good'
  test:
    query:
      - category == 'bottle' &
        data_type == 'test' &
        defect_type == 'good'
      - category == 'bottle' &
        data_type == 'test' &
        defect_type == 'broken_small'
      - category == 'bottle' &
        data_type == 'test' &
        defect_type == 'broken_large'
      - category == 'bottle' &
        data_type == 'test' &
        defect_type == 'contamination'

dataloader:
  train:
    args:
      batch_size: 32
      shuffle: True
  val:
    args:
      batch_size: 1
      shuffle: True
  test:
    args:
      batch_size: 1
      shuffle: True

optimizer:
  name: Adam
  args:
    lr: 0.0002
    weight_decay: 0.00001

criterion:
  name: MSELoss
  args:
    reduction: mean

run:
  train:
    epochs: 200
  val:
    data_num: 32
  test:
    batch_size: 32
    unfold_stride: 16
